spring.application.name=backend-order-service
server.port=8082
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

server.error.include-stacktrace=never
server.error.include-exception=false

server.servlet.context-path=/

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#Security config
#spring.security.user.name=pra
#spring.security.user.password=pass

jwt.secretKey=ahgvdahfuegfrgr8348098u409fvijknknjdjvkjkjfdnkawejhgcjgcutcrd6798y9t675675etfgc566yf